#!/usr/bin/python3

import re
import os
import sys
import argparse

from LDMS_Test import LDMSDCluster

parser = argparse.ArgumentParser(description = "List virtual clusters")
parser.add_argument("--long", "-l", action = "store_true",
                    help="Also list containers.")
parser.add_argument("--match", "-m", type=str, default='.*',
                    help="Regular expression for cluster name filtering")
args = parser.parse_args()

exp = re.compile(args.match)

clusters = LDMSDCluster.list()
clusters = [ c for c in clusters if exp.match(c.name) ]
if not clusters:
    if args.match == '.*':
        print("-- no cluster running --")
    else:
        print("-- no cluster matching: `{}` --".format(args.match))
for c in clusters:
    print(c.name)
    if args.long:
        print("  containers:")
        for cont in c.containers:
            print("    {} (on host {})".format(cont.name, cont.host))
