#!/usr/bin/python

import os
import sys
import docker
import argparse

from LDMS_Test import DockerCluster

parser = argparse.ArgumentParser(description = "Remove virtual clusters")
parser.add_argument("clusters", metavar = "CLUSTER", type=str, nargs="+",
                    help="Names of clusters to remove.")

args = parser.parse_args()
for name in args.clusters:
    try:
        cluster = DockerCluster.get(name = name)
    except docker.errors.NotFound:
        print("'{}' not found".format(name))
        continue
    print("Removing {} ...".format(name))
    cluster.remove()
    print(" ... done")
