#!/usr/bin/python3

import os
import sys
import docker
import argparse

from LDMS_Test import LDMSDCluster

parser = argparse.ArgumentParser(description = "Remove virtual clusters")
parser.add_argument("--all", action="store_true",
                    help="Remove all clusters")
parser.add_argument("clusters", metavar = "CLUSTER", type=str, nargs="*",
                    help="Names of clusters to remove.")

args = parser.parse_args()
if args.all:
    clusters = LDMSDCluster.list()
    names = [ c.name for c in clusters ]
else:
    names = args.clusters
for name in names:
    try:
        cluster = LDMSDCluster.get(name = name)
    except LookupError:
        print("'{}' not found".format(name))
        continue
    print("Removing {} ...".format(name), end='')
    cluster.remove()
    print(" done")
