#!/usr/bin/env python3

# The script tests the updtr_match_del configuration command

import argparse
import atexit
import errno
import logging
import json
import os
import sys
import TADA

from distutils.spawn import find_executable
from LDMS_Test import LDMSDCluster, LDMSDContainer, process_args, \
                      add_common_args, assertion_id_get, \
                      create_updtr_status, create_updtr_prdcr_status

if __name__ != "__main__":
    raise RuntimeError("This should not be imported as a module")

class Debug(object):
    pass
D = Debug()

logging.basicConfig(format = "%(asctime)s %(name)s %(levelname)s %(message)s",
                    level = logging.INFO)

log = logging.getLogger(__name__)

SCRIPT_DIR = os.path.realpath(sys.path[0])

#### default values #### ---------------------------------------------
sbin_ldmsd = find_executable("ldmsd")
if sbin_ldmsd:
    default_prefix, a, b = sbin_ldmsd.rsplit('/', 2)
else:
    default_prefix = "/opt/ovis"

LDMSD_PORT = 10000
LDMSD_XPRT = "sock"
RECONNECT_TIME = 1000000
UPDT_INTERVAL = 1000000
UPDT_OFFSET = 100000

id = assertion_id_get()

INVALID_REGEX      = next(id)
NON_EXISTING_UPDTR = next(id)
NON_EXISTING_MATCH_INST = next(id)
NON_EXISTING_MATCH_SCHEMA = next(id)
INVALID_MATCH      = next(id)
SUCCESS_INST       = next(id)
SUCCESS_SCHEMA     = next(id)

common_plugin_config = [
    "component_id=%component_id%",
    "instance=%hostname%/%plugin%",
    "producer=%hostname%",
]

spec = {
    "name" : "REPLACE_ME",
    "description" : "updtr_prdcdr_add_test cluster",
    "type" : "NA",
    "templates" : {
        "compute-node" : {
            "daemons" : [
                {
                    "name" : "sshd", # for debugging
                    "type" : "sshd",
                },
                {
                    "name" : "sampler-daemon",
                    "!extends" : "ldmsd-sampler",
                }
            ]
        },
        "sampler_plugin" : {
            "interval" : 1000000,
            "offset" : 0,
            "config" : common_plugin_config,
            "start" : True,
        },
        "ldmsd-base" : {
            "type" : "ldmsd",
            "listen" : [
                { "port" : LDMSD_PORT, "xprt" : LDMSD_XPRT }
            ]
        },
        "ldmsd-sampler" : {
            "!extends" : "ldmsd-base",
            "samplers" : [
                {
                    "plugin" : "meminfo",
                    "!extends" : "sampler_plugin",
                },
                {
                    "plugin" : "vmstat",
                    "!extends" : "sampler_plugin",
                }
            ]
        },
        "prdcr" : {
            "host" : "%name%",
            "xprt" : LDMSD_XPRT,
            "port" : LDMSD_PORT,
            "type" : "active",
            "interval" : RECONNECT_TIME,
        },
        "ldmsd-agg" : {
            "!extends" : "ldmsd-base",
            "prdcrs" : [
                {
                    "name" : "sampler-1",
                    "!extends" : "prdcr"
                },
                {
                    "name" : "sampler-2",
                    "!extends" : "prdcr",
                }
            ],
        },
    },
    "nodes" : [
        {
            "hostname" : "sampler-1",
            "component_id" : 10001,
            "!extends" : "compute-node",
        },
        {
            "hostname" : "sampler-2",
            "component_id" : 10002,
            "!extends" : "compute-node",
        },
        {
            "hostname" : "agg",
            "daemons" : [
                {
                    "name" : "sshd",
                    "type" : "sshd"
                },
                {
                    "name" : "agg",
                    "!extends" : "ldmsd-agg",
                    "config" : [
                        "prdcr_start_regex regex=.*",

                        "updtr_add name=invalid_regex interval={} offset={}" \
                                .format(UPDT_INTERVAL, UPDT_OFFSET),

                        "updtr_add name=all interval={} offset={}" \
                                .format(UPDT_INTERVAL, UPDT_OFFSET),
                        "updtr_prdcr_add name=all regex=.*",
                        "updtr_match_add name=all regex=meminfo match=inst",
                        "updtr_match_add name=all regex=vmstat match=schema",

                        "updtr_add name=running interval={} offset={}" \
                                .format(UPDT_INTERVAL, UPDT_OFFSET),
                        "updtr_prdcr_add name=running regex=.*",
                        "updtr_start name=running"
                    ]
                },
            ]
        },
    ],

    "cap_add" : ["SYS_PTRACE"],
    "image" : None,
    "ovis_prefix" : "REPLACE_ME",
    "mounts" : [],
    "env" : {}
}

@atexit.register
def at_exit():
    rc = test.finish()
    if cluster is not None:
        cluster.remove()
    os._exit(rc)

def ldmsd_request_send(dcont, cmd):
    x = "/db/ldmsd_request_send.py -x {xprt} -p {port} -H localhost --cmd '{cmd}'" \
        .format(xprt = LDMSD_XPRT, port = LDMSD_PORT, cmd = cmd)
    rc, out = dcont.exec_run(x)
    return (rc, out)

def get_updtr_status(dcont, name = None):
    if name is None:
        cmd = "updtr_status"
    else:
        cmd = "updtr_status name={}".format(name)
    (rc, out) = ldmsd_request_send(dcont, cmd)
    return (rc, out.strip())

def updtr_match_del(dcont, name, regex, m):
    cmd = "updtr_match_del name={} regex={} match={}".format(name, regex, m)
    (rc, out) = ldmsd_request_send(dcont, cmd)
    return (rc, out.strip())

if __name__ == "__main__":
    if sys.flags.interactive:
        exec(open(os.getenv("PYTHONSTARTUP", "/dev/null")).read())

    #### argument parsing #### -------------------------------------------
    ap = argparse.ArgumentParser(description = "Test the configuration command updtr_match_del")
    add_common_args(ap)
    args = ap.parse_args()
    process_args(args)

    spec["ovis_prefix"] = args.prefix
    spec["name"] = args.clustername
    spec["mounts"] += args.mount + ["{}:/db:rw".format(args.data_root)]
    if args.src:
        spec["mounts"] += { "{0}:{0}:ro".format(args.src)}
    spec["env"]["TADA_USER"] = args.user
    spec["env"]["TADA_ADDR"] = args.tada_addr
    spec["image"] = args.image

    #### Test Definition ####
    test = TADA.Test(test_suite = "LDMSD",
                     test_type = "FVT",
                     test_name = "updtr_add test",
                     test_desc = "Test updtr_add",
                     test_user = args.user,
                     commit_id = args.commit_id,
                     tada_addr = args.tada_addr,
                     )
    test.add_assertion(INVALID_REGEX,
                       "Send updtr_match_del with an invalid regex")
    test.add_assertion(NON_EXISTING_UPDTR,
                       "Send updtr_match_del to a non-existing updater")
    test.add_assertion(NON_EXISTING_MATCH_INST,
                       "Send updtr_match_del with a non-existing inst match")
    test.add_assertion(NON_EXISTING_MATCH_SCHEMA,
                       "Send updtr_match_del with a non-existing schema match")
    test.add_assertion(INVALID_MATCH,
                       "Send updater_match_del with an invalid match type")
    test.add_assertion(SUCCESS_INST,
                       "Send updater_match_del with a valid regex of the inst type")
    test.add_assertion(SUCCESS_SCHEMA,
                       "Send updater_match_del with a valid regex of the schema type")

    # --------------------------------------------------------------------------
    log.info("-- Get or create the cluster --")

    cluster = None
    test.start()

    cluster = LDMSDCluster.get(spec["name"], create = True, spec = spec)

    smplr1 = cluster.get_container("sampler-1")
    smplr2 = cluster.get_container("sampler-2")
    agg = cluster.get_container("agg")
    containers = [smplr1, smplr2, agg]

    for c in containers:
        c.write_file("/db/ldmsd_request_send.py", open(SCRIPT_DIR + "/ldmsd_request_send.py").read())
        c.exec_run("chmod 755 /db/ldmsd_request_send.py")

    log.info("-- Start daemons --")
    cluster.start_daemons()
    cluster.make_known_hosts()

    log.info("Waiting ... for all LDMSDs to start")
    while True:
        for c in containers:
            if c.check_ldmsd() is False:
                sleep(1)
                break
        break
    log.info("All LDMSDs are up.")

    # Invalid regex
    (rc, out) = updtr_match_del(agg, name = "invalid_regex", regex = "[", m = "inst")
    test.assert_test(INVALID_REGEX, rc == errno.ENOENT,
                     "report(rc = {}) == expect(rc = {})".format(rc, errno.EINVAL))

    # Non-existing updater
    (rc, out) = updtr_match_del(agg, name = "foo", regex = "[", m = "inst")
    test.assert_test(NON_EXISTING_UPDTR, rc == errno.ENOENT,
                     "report(rc = {}) == expect(rc = {})".format(rc, errno.ENOENT))

    # Non-existing regex of the inst match
    (rc, out) = updtr_match_del(agg, name = "all", regex = "foo", m = "inst")
    test.assert_test(NON_EXISTING_MATCH_INST, rc == errno.ENOENT,
                     "report(rc = {}) == expect(rc = {})".format(rc, errno.ENOENT))

    # Non-existing regex of the schema match
    (rc, out) = updtr_match_del(agg, name = "all", regex = "foo", m = "schema")
    test.assert_test(NON_EXISTING_MATCH_SCHEMA, rc == errno.ENOENT,
                     "report(rc = {}) == expect(rc = {})".format(rc, errno.ENOENT))

    # Invalid match type
    (rc, out) = updtr_match_del(agg, name = "all", regex = "meminfo", m = "foo")
    test.assert_test(INVALID_MATCH, rc == errno.EINVAL,
                     "report(rc = {}) == expect(rc = {})".format(rc, errno.EINVAL))

    # Valid regex with the inst match
    (rc, out) = updtr_match_del(agg, name = "all", regex = "meminfo", m = "inst")
    test.assert_test(SUCCESS_INST, rc == 0,
                     "report(rc = {}) == expect(rc = {})".format(rc, 0))

    # Valid regex with the schema match
    (rc, out) = updtr_match_del(agg, name = "all", regex = "vmstat", m = "schema")
    test.assert_test(SUCCESS_SCHEMA, rc == 0,
                     "report(rc = {}) == expect(rc = {})".format(rc, 0))

    log.info("--- done ---")
